baseURL = "https://scgmlz.github.io/scgdoc-hugo/"
theme = "scgclean"
languageCode = "en-us"
title = "My New Hugo Site"
MetaDataFormat = "toml"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200

[[menu.main]]
  name = "News"
  url = "/posts/"
  weight = -190

[[menu.main]]
  name = "Documentation"
  url = "/documentation/"
  weight = -180

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = -170


