baseURL = "https://scgmlz.github.io/BornAgain-website/"
theme = "hugo-theme-scgdoc"
languageCode = "en-us"
title = "BornAgain"
MetaDataFormat = "toml"
canonifyURLs = true

# Code
PygmentsCodeFences = true
PygmentsUseClassic = false
PygmentsUseClasses = true
PygmentsStyle = "vs"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Simulate and fit grazing insidence small angle scattering"
  Author = "James Bond"
  email = "contact@bornagainproject.org"
  custom_css = ["assets/css/bornagain.css"]
  version_major = "1"
  version_minor = "11"
  version_patch = "0"

[[params.social]]
    title = "github"
    url = "https://github.com/scgmlz/BornAgain"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200

[[menu.main]]
  name = "News"
  url = "/news/"
  weight = -190

[[menu.main]]
  name = "Documentation"
  url = "/documentation/"
  weight = -180

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = -170

